// Centralized Mock Data System for DONOR ↔ RECEIVER BRIDGE PLATFORM

export const MOCK_NGOS = [
  {
    id: 'ngo-101',
    name: 'Helping Hands Foundation',
    verified: true,
    verificationStatus: 'VERIFIED_PARTNER',
    addressVerified: true,
    logo: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=150&auto=format&fit=crop&q=80',
    description: 'Dedicated to mitigating urban hunger and supporting under-resourced schools with essential meals and study materials.',
    city: 'Pune',
    area: 'Shivajinagar',
    address: '42 University Road, Shivajinagar, Pune',
    location: { lat: 18.5308, lng: 73.8474 },
    distanceKm: 2.4,
    phone: '+91 98220 11223',
    email: 'contact@helpinghands.org',
    website: 'https://helpinghands.org.in',
    foodTypesAccepted: ['Cooked Food', 'Raw Grains', 'Packaged Food', 'Bakery Items'],
    capacity: '800 meals/day',
    areasOfSupport: ['Food Security', 'Educational Materials', 'Clothes & Blankets'],
    beneficiariesCount: 1450,
    pastDonationsCount: 320,
    impactScore: '98%',
    currentRequirements: [
      { id: 'req-1', item: 'Rice & Pulses', category: 'Food', quantity: 50, unit: 'kg', urgency: 'HIGH', requiredBy: '2026-08-20', beneficiaries: 120 },
      { id: 'req-2', item: 'School Textbooks (Std 5-8)', category: 'Books', quantity: 40, unit: 'Sets', urgency: 'MEDIUM', requiredBy: '2026-08-25', beneficiaries: 40 }
    ]
  },
  {
    id: 'ngo-102',
    name: 'Food Relief Foundation',
    verified: true,
    verificationStatus: 'VERIFIED_PARTNER',
    addressVerified: true,
    logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=150&auto=format&fit=crop&q=80',
    description: 'Providing daily hot meals and surplus food redistribution to street shelters and community kitchens across Pune.',
    city: 'Pune',
    area: 'Kothrud',
    address: '18 Paud Road, Kothrud, Pune',
    location: { lat: 18.5074, lng: 73.8077 },
    distanceKm: 5.1,
    phone: '+91 98221 44556',
    email: 'help@foodrelief.org',
    website: 'https://foodrelief.org.in',
    foodTypesAccepted: ['Fresh Cooked Meals', 'Vegetables', 'Fruits', 'Edible Oil'],
    capacity: '1200 meals/day',
    areasOfSupport: ['Surplus Food Distribution', 'Emergency Rations', 'Community Kitchens'],
    beneficiariesCount: 2800,
    pastDonationsCount: 640,
    impactScore: '96%',
    currentRequirements: [
      { id: 'req-3', item: 'Fresh Cooked Meals', category: 'Food', quantity: 100, unit: 'Portions', urgency: 'HIGH', requiredBy: '2026-08-17', beneficiaries: 100 },
      { id: 'req-4', item: 'Cooking Oil', category: 'Food', quantity: 20, unit: 'Liters', urgency: 'MEDIUM', requiredBy: '2026-08-22', beneficiaries: 80 }
    ]
  },
  {
    id: 'ngo-103',
    name: 'Seva Asha Community Shelter',
    verified: true,
    verificationStatus: 'VERIFIED_PARTNER',
    addressVerified: true,
    logo: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=150&auto=format&fit=crop&q=80',
    description: 'Shelter home supporting homeless families, women, and children with shelter, warm clothes, and basic healthcare supplies.',
    city: 'Pune',
    area: 'Viman Nagar',
    address: '89 Nagar Road, Viman Nagar, Pune',
    location: { lat: 18.5679, lng: 73.9143 },
    distanceKm: 7.8,
    phone: '+91 98225 77889',
    email: 'info@sevaasha.org',
    website: 'https://sevaasha.org',
    foodTypesAccepted: ['Packaged Rations', 'Dry Snacks', 'Milk & Dairy'],
    capacity: '400 meals/day',
    areasOfSupport: ['Clothes', 'Medical Supplies', 'Electronics / Appliances'],
    beneficiariesCount: 920,
    pastDonationsCount: 210,
    impactScore: '99%',
    currentRequirements: [
      { id: 'req-5', item: 'Winter Jackets & Blankets', category: 'Clothes', quantity: 60, unit: 'Pieces', urgency: 'HIGH', requiredBy: '2026-08-19', beneficiaries: 60 },
      { id: 'req-6', item: 'First Aid Supplies & Antiseptics', category: 'Medical Supplies', quantity: 15, unit: 'Kits', urgency: 'HIGH', requiredBy: '2026-08-18', beneficiaries: 150 }
    ]
  },
  {
    id: 'ngo-104',
    name: 'Robin Hood Army (Pune Chapter)',
    verified: true,
    verificationStatus: 'VERIFIED_PARTNER',
    addressVerified: true,
    logo: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb0?w=150&auto=format&fit=crop&q=80',
    description: 'Volunteer-driven organization serving surplus food from restaurants and events to less fortunate communities.',
    city: 'Pune',
    area: 'Deccan Gymkhana',
    address: 'Deccan Volunteer Hub, Pune',
    location: { lat: 18.5186, lng: 73.8415 },
    distanceKm: 1.8,
    phone: '+91 98900 12345',
    email: 'pune@robinhoodarmy.com',
    website: 'https://robinhoodarmy.com',
    foodTypesAccepted: ['Cooked Buffet Surplus', 'Bread & Bakery', 'Curry & Rice'],
    capacity: '2500 meals/day',
    areasOfSupport: ['Night Drives', 'Slum Distribution', 'School Meals'],
    beneficiariesCount: 5000,
    pastDonationsCount: 1200,
    impactScore: '99%',
    currentRequirements: [
      { id: 'req-rha-1', item: 'Event Leftover Dinners', category: 'Food', quantity: 150, unit: 'Portions', urgency: 'HIGH', requiredBy: '2026-08-16', beneficiaries: 150 }
    ]
  },
  {
    id: 'ngo-105',
    name: 'Feeding India (Zomato Giving)',
    verified: true,
    verificationStatus: 'VERIFIED_PARTNER',
    addressVerified: true,
    logo: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=150&auto=format&fit=crop&q=80',
    description: 'National non-profit eliminating hunger and malnutrition through structured food rescue networks.',
    city: 'Pune',
    area: 'Kharadi',
    address: 'Kharadi Rescue Hub, Pune',
    location: { lat: 18.5520, lng: 73.9350 },
    distanceKm: 9.1,
    phone: '+91 98888 77766',
    email: 'contact@feedingindia.org',
    website: 'https://feedingindia.org',
    foodTypesAccepted: ['Cooked Food', 'Raw Grains', 'Packaged Rations'],
    capacity: '3000 meals/day',
    areasOfSupport: ['Poshan Centers', 'Emergency Disaster Relief'],
    beneficiariesCount: 8200,
    pastDonationsCount: 2100,
    impactScore: '98%',
    currentRequirements: [
      { id: 'req-fi-1', item: 'Dry Ration Packets', category: 'Food', quantity: 200, unit: 'Packs', urgency: 'HIGH', requiredBy: '2026-08-22', beneficiaries: 200 }
    ]
  }
];

export const MOCK_INITIAL_DONATIONS = [
  {
    id: 'DON-2026-00501',
    title: '60 Servings Veg Biryani & Paneer Curry',
    category: 'Food',
    itemName: 'Veg Biryani & Paneer Curry',
    excessDetails: 'Freshly packed commercial buffet surplus in thermal foil containers',
    quantity: 60,
    unit: 'servings',
    foodType: 'Cooked Food',
    description: 'Hot vegetarian cooked meals prepared for lunch buffet, untouched and ready for redistribution.',
    condition: 'Fresh / Cooked Today',
    pickupLocation: 'FC Road, Deccan Gymkhana, Pune',
    pickupCoords: { lat: 18.5196, lng: 73.8412 },
    ngoCoords: null,
    volunteerId: null,
    volunteerName: null,
    volunteerPhone: null,
    volunteerCoords: null,
    availabilityDate: '2026-08-23',
    availabilityTime: '18:00 - 22:00',
    expiryDate: '2026-08-24T02:00:00Z',
    expiryTime: '2026-08-24T02:00:00Z',
    urgency: 'HIGH',
    notes: 'Please collect from the side dispatch door.',
    status: 'AVAILABLE',
    matchedNgoId: null,
    matchedNgoName: null,
    createdAt: '2026-08-23T14:30:00Z',
    donorName: 'Green Bite Restaurant & Catering',
    donorPhone: '+91 98111 22334',
    trackingTimeline: [
      { status: 'CREATED', label: 'Donation Created', timestamp: '2026-08-23T14:30:00Z', completed: true },
      { status: 'MATCHED', label: 'Receiver Matched', timestamp: null, completed: false },
      { status: 'VOLUNTEER_ASSIGNED', label: 'Volunteer Assigned 🚴', timestamp: null, completed: false },
      { status: 'FOOD_PICKED_UP', label: 'Food Picked Up 🍱', timestamp: null, completed: false },
      { status: 'IN_TRANSIT', label: 'Out for Delivery 🚚', timestamp: null, completed: false },
      { status: 'DELIVERED', label: 'Delivered to NGO 📍', timestamp: null, completed: false }
    ]
  },
  {
    id: 'DON-2026-00502',
    title: '35 kg Fresh Seasonal Vegetables & Fruits',
    category: 'Food',
    itemName: 'Seasonal Produce Box',
    excessDetails: '35 kg sorted fresh tomatoes, potatoes, spinach, and apples',
    quantity: 35,
    unit: 'kg',
    foodType: 'Raw Produce',
    description: 'Fresh farm-sourced produce crates suitable for community kitchen cooking.',
    condition: 'Fresh / Raw',
    pickupLocation: 'Market Yard, Gultekdi, Pune',
    pickupCoords: { lat: 18.4890, lng: 73.8680 },
    ngoCoords: null,
    volunteerId: null,
    volunteerName: null,
    volunteerPhone: null,
    volunteerCoords: null,
    availabilityDate: '2026-08-23',
    availabilityTime: '10:00 - 20:00',
    expiryDate: '2026-08-25T18:00:00Z',
    expiryTime: '2026-08-25T18:00:00Z',
    urgency: 'MEDIUM',
    notes: 'Crates packed and ready in loading bay 3.',
    status: 'AVAILABLE',
    matchedNgoId: null,
    matchedNgoName: null,
    createdAt: '2026-08-23T12:00:00Z',
    donorName: 'AgroFresh Wholesale Co.',
    donorPhone: '+91 98224 88990',
    trackingTimeline: [
      { status: 'CREATED', label: 'Donation Created', timestamp: '2026-08-23T12:00:00Z', completed: true },
      { status: 'MATCHED', label: 'Receiver Matched', timestamp: null, completed: false },
      { status: 'VOLUNTEER_ASSIGNED', label: 'Volunteer Assigned 🚴', timestamp: null, completed: false },
      { status: 'FOOD_PICKED_UP', label: 'Food Picked Up 🍱', timestamp: null, completed: false },
      { status: 'IN_TRANSIT', label: 'Out for Delivery 🚚', timestamp: null, completed: false },
      { status: 'DELIVERED', label: 'Delivered to NGO 📍', timestamp: null, completed: false }
    ]
  },
  {
    id: 'DON-2026-00482',
    title: '50 kg Basmati Rice & Grain Stock',
    category: 'Food',
    itemName: 'Basmati Rice',
    excessDetails: '50 kg surplus raw Basmati rice sacks from restaurant inventory',
    quantity: 50,
    unit: 'kg',
    foodType: 'Cooked Food',
    description: 'Sealed 25kg sacks of premium Basmati rice, freshly sourced for donation.',
    condition: 'New / Sealed',
    pickupLocation: 'FC Road, Deccan Gymkhana, Pune',
    pickupCoords: { lat: 18.5196, lng: 73.8412 },
    ngoCoords: { lat: 18.5308, lng: 73.8474 },
    volunteerId: 'vol-201',
    volunteerName: 'Rahul Verma (Rider)',
    volunteerPhone: '+91 98233 44112',
    volunteerCoords: { lat: 18.5240, lng: 73.8445 },
    availabilityDate: '2026-08-17',
    availabilityTime: '14:00 - 18:00',
    urgency: 'HIGH',
    notes: 'Please collect from the back kitchen gate.',
    status: 'VOLUNTEER_ASSIGNED',
    matchedNgoId: 'ngo-101',
    matchedNgoName: 'Helping Hands Foundation',
    createdAt: '2026-08-16T10:30:00Z',
    donorName: 'Green Bite Restaurant',
    donorPhone: '+91 98111 22334',
    trackingTimeline: [
      { status: 'CREATED', label: 'Donation Created', timestamp: '2026-08-16T10:30:00Z', completed: true },
      { status: 'MATCHED', label: 'Receiver Matched', timestamp: '2026-08-16T11:15:00Z', completed: true },
      { status: 'VOLUNTEER_ASSIGNED', label: 'Volunteer Assigned 🚴', timestamp: '2026-08-16T11:45:00Z', completed: true },
      { status: 'FOOD_PICKED_UP', label: 'Food Picked Up 🍱', timestamp: null, completed: false },
      { status: 'IN_TRANSIT', label: 'Out for Delivery 🚚', timestamp: null, completed: false },
      { status: 'DELIVERED', label: 'Delivered to NGO 📍', timestamp: null, completed: false }
    ]
  },
  {
    id: 'DON-2026-00391',
    title: '40 Hot Meals Catering Surplus',
    category: 'Food',
    itemName: 'Paneer Butter Masala & Rotis',
    excessDetails: '40 hot cooked meal trays from wedding event catering excess',
    quantity: 40,
    unit: 'Portions',
    foodType: 'Cooked Food',
    description: 'Freshly prepared vegetarian meals packed in thermal containers.',
    condition: 'Fresh / Cooked Today',
    pickupLocation: 'Aundh DP Road, Pune',
    pickupCoords: { lat: 18.5602, lng: 73.8031 },
    ngoCoords: { lat: 18.5679, lng: 73.9143 },
    volunteerId: 'vol-202',
    volunteerName: 'Priya Sharma (Volunteer)',
    volunteerPhone: '+91 98999 11223',
    volunteerCoords: { lat: 18.5640, lng: 73.8500 },
    availabilityDate: '2026-08-16',
    availabilityTime: '18:00 - 21:00',
    urgency: 'HIGH',
    notes: 'Hot food packed in insulated foil containers.',
    status: 'IN_TRANSIT',
    matchedNgoId: 'ngo-103',
    matchedNgoName: 'Seva Asha Community Shelter',
    createdAt: '2026-08-16T12:00:00Z',
    donorName: 'Royal Spice Caterers',
    donorPhone: '+91 98222 55667',
    trackingTimeline: [
      { status: 'CREATED', label: 'Donation Created', timestamp: '2026-08-16T12:00:00Z', completed: true },
      { status: 'MATCHED', label: 'Receiver Matched', timestamp: '2026-08-16T12:20:00Z', completed: true },
      { status: 'VOLUNTEER_ASSIGNED', label: 'Volunteer Assigned 🚴', timestamp: '2026-08-16T12:35:00Z', completed: true },
      { status: 'FOOD_PICKED_UP', label: 'Food Picked Up 🍱', timestamp: '2026-08-16T13:10:00Z', completed: true },
      { status: 'IN_TRANSIT', label: 'Out for Delivery 🚚', timestamp: '2026-08-16T13:25:00Z', completed: true },
      { status: 'DELIVERED', label: 'Delivered to NGO 📍', timestamp: null, completed: false }
    ]
  },
  {
    id: 'DON-2026-00215',
    title: '15 Refurbished School Laptops',
    category: 'Electronics',
    itemName: 'Dell & HP Laptops',
    excessDetails: '15 corporate surplus laptops reset for student digital labs',
    quantity: 15,
    unit: 'Units',
    foodType: 'Other',
    description: 'Working laptops with Windows 10 & educational apps pre-installed.',
    condition: 'Refurbished',
    pickupLocation: 'Kharadi IT Park, Pune',
    pickupCoords: { lat: 18.5515, lng: 73.9348 },
    ngoCoords: { lat: 18.5089, lng: 73.9260 },
    volunteerId: 'vol-203',
    volunteerName: 'Amit Deshmukh',
    volunteerPhone: '+91 98765 43210',
    volunteerCoords: { lat: 18.5089, lng: 73.9260 },
    availabilityDate: '2026-08-12',
    availabilityTime: '11:00 - 17:00',
    urgency: 'HIGH',
    notes: 'Chargers and carry bags included.',
    status: 'DELIVERED',
    matchedNgoId: 'ngo-104',
    matchedNgoName: 'Gyan Jyoti Shikshan Trust',
    createdAt: '2026-08-11T14:00:00Z',
    donorName: 'TechSolutions Pvt Ltd',
    donorPhone: '+91 98765 43210',
    trackingTimeline: [
      { status: 'CREATED', label: 'Donation Created', timestamp: '2026-08-11T14:00:00Z', completed: true },
      { status: 'MATCHED', label: 'Receiver Matched', timestamp: '2026-08-11T15:30:00Z', completed: true },
      { status: 'VOLUNTEER_ASSIGNED', label: 'Volunteer Assigned 🚴', timestamp: '2026-08-12T09:30:00Z', completed: true },
      { status: 'FOOD_PICKED_UP', label: 'Food Picked Up 🍱', timestamp: '2026-08-12T11:45:00Z', completed: true },
      { status: 'IN_TRANSIT', label: 'Out for Delivery 🚚', timestamp: '2026-08-12T13:00:00Z', completed: true },
      { status: 'DELIVERED', label: 'Delivered to NGO 📍', timestamp: '2026-08-12T14:15:00Z', completed: true }
    ]
  }
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'Volunteer Assigned! 🚴',
    message: 'Rahul Verma accepted pickup for donation DON-2026-00482.',
    time: '5 mins ago',
    read: false,
    type: 'INFO'
  },
  {
    id: 'notif-2',
    title: 'Food Picked Up 🍱',
    message: 'Donation DON-2026-00391 has been picked up from donor address.',
    time: '1 hour ago',
    read: false,
    type: 'SUCCESS'
  },
  {
    id: 'notif-3',
    title: 'Out for Delivery 🚚',
    message: 'Volunteer is en route to Seva Asha Shelter.',
    time: '2 hours ago',
    read: true,
    type: 'WARNING'
  }
];
